services:
  - type: web
    name: smartbnb
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./smartbnb/Dockerfile
    autoDeployTrigger: checksPass
    healthCheckPath: /api/health
    previewsEnabled: false
    buildFilter:
      paths:
        - smartbnb/frontend/**
        - smartbnb/backend/**
        - smartbnb/Dockerfile
        - render.yaml
    build:
      args:
        VITE_API_BASE: /api
